server:
  port: 8091

spring:
  application:
    name: microservicio-carrito-compras
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:configserver:http://localhost:8097/
