server:
  port: 8093

spring:
  application:
    name: microservicio-ordenes-pagos
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:configserver:http://localhost:8097/

